name: "dqn_prison"
buffer_size: 100_000
critic_learning_rate: 0.0001
critic_learning_start: 10000
critic_batch_size: 256
critic_update_rate: 1000
critic_num_sgd_steps_per_update_iter: 16
tau: 0.8

impact_batch_size: 256
impact_update_rate: 32
tim_initial_step_size: 0.05
tim_step_size_decay: 0.9999
sim_learning_rate: 0.0005
hidden_layer_size: 32

